### PR TITLE
Fix: Filter EVM logs instead of subscriptions

### LINKED ISSUE #318: Validator Nodes Fatally Crash on RPC Timeout
ABOUT:
Validator nodes will fatally crash on receiving HTTP timeouts from RPC calls to the Node Urls. This issue happens both when the bridge is being used and also when no transactions are going through bridge. If there is a bad response from Infura or other RPC providers, it will cause the node to crash and requires a manual restart.

LOGS:
`ERRO[2021-10-21T03:50:43.2332205Z] Failed to subscribe for Burn Event Logs for contract address [OMITTED]. Error [websocket: bad handshake (HTTP status 502 Bad Gateway)].  context="EVM Router Watcher [OMITTED]"
FATA[2021-10-21T03:50:43.448793149Z] Failed to subscribe for WatchMemberUpdated Event Logs for contract. Error websocket: bad handshake (HTTP status 502 Bad Gateway)  context="Contract Service"
exit status 1`

Expected Behaviour:
If node receives a HTTP timeout or 502 from RPC it should not fatally exit, instead it should re-poll the RPC at a later time and remain running.

### PR DESCRIPTION
**Pull request by failfmi**
**Detailed description**:
* Filter EVM logs instead of subscriptions

**Which issue(s) this PR fixes**:
Fixes #318 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

File: app/process/watcher/evm/watcher.go [hunk 1]
```diff
@@ -85,58 +91,95 @@ func NewWatcher(
...
 
 	topics := [][]common.Hash{
 		{
 			burnHash,
 			lockHash,
+			memberUpdatedHash,
 		},
 	}
 	addresses := []common.Address{
 		ew.contracts.Address(),
```
Comment (Daniel-K-Ivanov) [inline app/process/watcher/evm/watcher.go:169]: Are we 100% sure that events with the same signature, emitted in a `router` TX will be ignored

File: app/process/watcher/evm/watcher.go [hunk 2]
```diff
@@ -85,58 +91,95 @@ func NewWatcher(
...
 	}
+
 	query := &ethereum.FilterQuery{
 		FromBlock: new(big.Int).SetInt64(fromBlock),
+		ToBlock:   new(big.Int).SetInt64(endBlock),
 		Addresses: addresses,
 		Topics:    topics,
 	}
+
 	logs, err := ew.evmClient.FilterLogs(context.Background(), *query)
```
Comment (Daniel-K-Ivanov) [inline app/process/watcher/evm/watcher.go:179]: FYI: If there are more than 1000 events matching this `FilterLog` the node will reject the query and will throw `>400` status

File: app/process/watcher/evm/watcher.go [hunk 3]
```diff
@@ -85,58 +91,95 @@ func NewWatcher(
...
+		if fromBlock > toBlock {
+			time.Sleep(ew.sleepDuration)
+			continue
+		}
+
+		err = ew.processLogs(fromBlock, toBlock, queue)
+		if err != nil {
+			ew.logger.Errorf("Failed to process logs. Error: [%s].", err)
+			time.Sleep(ew.sleepDuration)
+			continue
```
Comment (Daniel-K-Ivanov) [inline app/process/watcher/evm/watcher.go:143]: nit: we do not need those 2 lines of code

**Review by Daniel-K-Ivanov — CHANGES_REQUESTED** [review]
- In evm/watcher.go -> line 317 you need to update the `Debugf` not to state that we are waiting for block confirmations

File: app/clients/evm/client.go [hunk 4]
```diff
@@ -84,14 +84,16 @@ func (ec *Client) ValidateContractDeployedAt(contractAddress string) (*common.Ad
 }
 
 // GetBlockTimestamp retrieves the timestamp of the given block
-func (ec *Client) GetBlockTimestamp(blockNumber *big.Int) (uint64, error) {
+func (ec *Client) GetBlockTimestamp(blockNumber *big.Int) uint64 {
```
[the remark this answers is not in the document]
Comment (failfmi) [reply app/clients/evm/client.go:87]: I think it would better to hang and retry than to end the processing of a given transfer, just because something has timed out

File: app/process/watcher/evm/watcher.go [hunk 5]
```diff
@@ -85,58 +91,95 @@ func NewWatcher(
...
 
-func (ew Watcher) processPastLogs(queue qi.Queue) {
+func (ew Watcher) beginWatching(queue qi.Queue) {
 	fromBlock, err := ew.repository.Get(ew.contracts.Address().String())
 	if err != nil {
 		ew.logger.Errorf("Failed to retrieve EVM Watcher Status fromBlock. Error: [%s]", err)
-		return
 	}
 
 	ew.logger.Infof("Processing events from [%d]", fromBlock)
```
[the remark this answers is not in the document]
Comment (failfmi) [reply app/process/watcher/evm/watcher.go:117]: 1. yes
2. yes,  it used to be fatalf

File: app/process/watcher/evm/watcher.go (hunk 1 above)
Comment (failfmi) [reply app/process/watcher/evm/watcher.go:169]: That's why you are filtering by `addresses`. They are used to restrict matches to events created by those specific addresses.

File: app/process/watcher/evm/watcher.go (hunk 3 above)
Comment (failfmi) [reply app/process/watcher/evm/watcher.go:143]: I've left them on purpose, so that if the error is timeout related, it will pause for a bit, rather than trying again immediately

File: app/process/watcher/evm/watcher.go (hunk 2 above)
Comment (failfmi) [reply app/process/watcher/evm/watcher.go:207]: The limitation should based in the querying node. I guess we will adapt depending on the node config.

File: app/process/watcher/evm/watcher.go (hunk 3 above)
Comment (Daniel-K-Ivanov) [reply app/process/watcher/evm/watcher.go:194]: Aren't we going to pause for a bit even if we remove those 2 lines because of line 197?

**Review by Daniel-K-Ivanov — DISMISSED** [review]

**Review by Daniel-K-Ivanov — APPROVED** [review]
